version: '3'
services:
  app:
    build: .
    ports:
     - 8080:5000
    volumes:
     - .:/app
    depends_on:
     - sqlitedb
    links:
     - sqlitedb
    entrypoint:
     - python3
     - -u
     - ethereum/app.py

  worker:
    build: .
    volumes:
      - .:/app
    depends_on:
      - sqlitedb
    links:
      - sqlitedb
    entrypoint:
      - python3
      - -u
      - ethereum/worker.py

  sqlitedb:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
