version: '2'
services:
  app:
    build: .
    ports:
     - 8080:5000
    volumes:
     - .:/app
    depends_on:
     - sqlitedb
    links:
     - sqlitedb
  worker:
    build: .
    volumes:
      - .:/worker
    depends_on:
      - sqlitedb
    links:
      - sqlitedb
  sqlitedb:
    image: sqlite3:latest
    ports:
        - 27017:27017
    volumes:
      - ./db/:/root/db/