version: '3'
services:
  app:
    build: .
    ports:
     - 8080:5000
    volumes:
     - .:/app
    depends_on:
     - sqlitedb
    links:
     - sqlitedb

  sqlitedb:
    image: sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
